-- ====================================================================
-- LATINOS EN PELOTA - SEGURIDAD Y CONFIGURACIÓN EN SUPABASE
-- ====================================================================
-- Este script configura la base de datos para que:
-- 1. Cualquier visitante del sitio web pueda LEER noticias y categorías.
-- 2. SOLO los administradores que inicien sesión puedan CREAR, MODIFICAR
--    o ELIMINAR categorías y noticias, y subir imágenes.
-- ====================================================================

-- 1. TABLA CATEGORIAS
CREATE TABLE IF NOT EXISTS public.categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE
);

-- 2. TABLA NOTICIAS
CREATE TABLE IF NOT EXISTS public.noticias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    titulo TEXT NOT NULL,
    subtitulo TEXT,
    contenido TEXT NOT NULL,
    categoria_id BIGINT REFERENCES public.categorias(id) ON DELETE SET NULL,
    imagen_url TEXT,
    estado TEXT DEFAULT 'borrador',
    publicado_en TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SEGURIDAD A NIVEL DE FILA (ROW LEVEL SECURITY - RLS)
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.noticias ENABLE ROW LEVEL SECURITY;

-- Limpieza de políticas previas
DROP POLICY IF EXISTS "Lectura publica categorias" ON public.categorias;
DROP POLICY IF EXISTS "Admins insert categorias" ON public.categorias;
DROP POLICY IF EXISTS "Admins update categorias" ON public.categorias;
DROP POLICY IF EXISTS "Admins delete categorias" ON public.categorias;
DROP POLICY IF EXISTS "Permitir todo categorias" ON public.categorias;
DROP POLICY IF EXISTS "Permitir select en categorias" ON public.categorias;
DROP POLICY IF EXISTS "Permitir insert en categorias" ON public.categorias;
DROP POLICY IF EXISTS "Permitir update en categorias" ON public.categorias;
DROP POLICY IF EXISTS "Permitir delete en categorias" ON public.categorias;

-- Políticas para 'categorias':
-- Lectura pública para cualquier usuario visitante
CREATE POLICY "Lectura publica categorias"
ON public.categorias FOR SELECT
USING (true);

-- Solo usuarios autenticados (administradores con sesión iniciada) pueden modificar:
CREATE POLICY "Admins insert categorias"
ON public.categorias FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Admins update categorias"
ON public.categorias FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Admins delete categorias"
ON public.categorias FOR DELETE
TO authenticated
USING (true);

-- Políticas para 'noticias':
DROP POLICY IF EXISTS "Lectura publica noticias" ON public.noticias;
DROP POLICY IF EXISTS "Admins insert noticias" ON public.noticias;
DROP POLICY IF EXISTS "Admins update noticias" ON public.noticias;
DROP POLICY IF EXISTS "Admins delete noticias" ON public.noticias;
DROP POLICY IF EXISTS "Permitir todo noticias" ON public.noticias;
DROP POLICY IF EXISTS "Permitir select en noticias" ON public.noticias;
DROP POLICY IF EXISTS "Permitir insert en noticias" ON public.noticias;
DROP POLICY IF EXISTS "Permitir update en noticias" ON public.noticias;
DROP POLICY IF EXISTS "Permitir delete en noticias" ON public.noticias;

-- Lectura pública de noticias
CREATE POLICY "Lectura publica noticias"
ON public.noticias FOR SELECT
USING (true);

-- Solo administradores autenticados pueden crear, modificar o eliminar noticias
CREATE POLICY "Admins insert noticias"
ON public.noticias FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Admins update noticias"
ON public.noticias FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Admins delete noticias"
ON public.noticias FOR DELETE
TO authenticated
USING (true);

-- 4. BUCKET DE IMÁGENES PÚBLICO
INSERT INTO storage.buckets (id, name, public)
VALUES ('imagenes', 'imagenes', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de Storage
DROP POLICY IF EXISTS "Lectura publica imagenes" ON storage.objects;
DROP POLICY IF EXISTS "Admins subir imagenes" ON storage.objects;
DROP POLICY IF EXISTS "Admins borrar imagenes" ON storage.objects;
DROP POLICY IF EXISTS "Permitir subir imagenes" ON storage.objects;
DROP POLICY IF EXISTS "Permitir ver imagenes publicas" ON storage.objects;
DROP POLICY IF EXISTS "Permitir ver imagenes" ON storage.objects;
DROP POLICY IF EXISTS "Permitir eliminar imagenes" ON storage.objects;

-- Cualquier visitante puede ver las imágenes en las noticias
CREATE POLICY "Lectura publica imagenes"
ON storage.objects FOR SELECT
USING (bucket_id = 'imagenes');

-- Solo administradores autenticados pueden subir fotos
CREATE POLICY "Admins subir imagenes"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'imagenes');

CREATE POLICY "Admins borrar imagenes"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'imagenes');

-- 5. CATEGORÍAS BASE
INSERT INTO public.categorias (nombre) VALUES
    ('Béisbol'),
    ('Fútbol'),
    ('Baloncesto'),
    ('Boxeo'),
    ('Atletismo'),
    ('Tenis')
ON CONFLICT (nombre) DO NOTHING;
